# -*- coding: utf-8 -*-
"""gcm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HgcDOzR1ernCx1ARv02GS0al_b2rr8sO
"""

def gcd(a, b):
  print(str(a)+" "+str(b)+"\n")
  if b == 0:
    return a
  else:
    return gcd(b, (a % b))

gcd(1220,516)
